spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: rootpassword
      database: order_db
      port: 27017
      host: localhost
  webflux:
    base-path: /api

