openapi: 3.0.3
info:
  version: v1.0
  title: Payment API
  description: 'Payment API specification'
tags:
  - name: Payment API Endpoints
    description: Create Payment, Add Payment Item and Complete Payment.
servers:
  - description: localhost WebApp
    url: http://localhost:8080

paths:
  /api/v1/payments:
    post:
      tags:
        - Payment
      summary: Create Payment.
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentDto"
      responses:
        200:
          description: Payment has been created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponseDto"
        400:
          description: Bad Request, invalid request body supplied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorFieldResponseDto"
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
  /api/v1/payments/{payment-id}/items:
    put:
      tags:
        - Payment
      summary: Add item to Payment.
      operationId: addPaymentItem
      parameters:
        - in: path
          name: payment-id
          schema:
            type: integer
          required: true
          description: Generated Payment ID from Create Payment operation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentDto"
      responses:
        200:
          description: Payment item has been added.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponseDto"
        400:
          description: Bad Request, invalid request body supplied.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorFieldResponseDto"
        409:
          description: Unable to perform operation, payment state conflict occurred, (example. Payment already completed).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorFieldResponseDto"
        404:
          description: Unable to find supplied Payment ID in DB.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
  /api/v1/payments/{payment-id}/completed:
    put:
      tags:
        - Payment
      summary: Finalized and completed Payment cycle (definition and next step is TBD ;) ).
      operationId: completePayment
      parameters:
        - in: path
          name: payment-id
          schema:
            type: integer
          required: true
          description: Generated Payment ID from Create Payment operation.
      responses:
        200:
          description: Payment has been completed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponseDto"
        404:
          description: Unable to find supplied Payment ID in DB.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
        409:
          description: Unable to perform operation, payment state conflict occurred, (example. Payment already completed).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorFieldResponseDto"
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseDto"
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    PaymentDto:
      type: object
      properties:
        amount:
          type: number
          description: Amount
    PaymentItemDto:
      type: object
      properties:
        id:
          type: number
          example: 1
          description: Number of Payment
        amount:
          type: number
          example: 20.0
          description: Amount
    PaymentResponseDto:
      type: object
      properties:
        id:
          type: number
          description: Number of Payment
          example: 1
        status:
          type: string
          enum:
            - CREATED
            - COMPLETED
            - CANCELLED
          description: Payment Status
        items:
          type: array
          items:
            $ref: '#/components/schemas/PaymentItemDto'
          description: Payment Items
    ErrorResponseDto:
      type: object
      properties:
        errorMessage:
          type: string
          description: Error Message
    ErrorFieldResponseDto:
      type: object
      properties:
        errorMessage:
          type: string
          description: Error Message
        errorFields:
          type: array
          items:
            $ref: '#/components/schemas/ErrorFieldDto'
    ErrorFieldDto:
      type: object
      properties:
        name:
          type: string
          description: Field name that invalid
        message:
          type: string
          description: Description of the error